### ISSUE TITLE
Datasets dir DNE

### ISSUE THREAD

**Issue by tristenwentling** [newfront/hitchhikers_guide_to_deltalake_streaming#3]
Running the ecomm_csv_to_parquet.ipynb nb cell(3)
```
# read and process initial dataset

ecomm_df = (
    spark.read.format("csv")
    .option("header", True)
    .schema(schema)
    .load(f"{dataset_dir}/{datasets[0]}")
)
```
gives the following error:
`AnalysisException: Path does not exist: file:/opt/spark/work-dir/hitchhikers_guide/datasets/ecomm_behavior_data/2019-Oct-sm.csv`
Looking at the leading directories I only see:
```
os.listdir('/opt/spark/work-dir/hitchhikers_guide')

['first-steps', 'pre-processing', 'when-things-go-bump-in-the-night']
```

I think getting the dataset is maybe not included in the docker compose
I did see it in the repo and copied it in manually and it works fine

**Comment by tristenwentling** [comment]
looked at the PR, might be moot

**Comment by newfront** [comment]
Yeah I botched the mount location in the non-arm docker-compose. Just made the change.

**Comment by newfront** [comment]
<img width="881" alt="Screenshot 2023-06-22 at 1 42 33 PM" src="https://github.com/newfront/hitchhikers_guide_to_deltalake_streaming/assets/460318/87077702-c179-4661-af3a-6be295896b31">
