### ISSUE TITLE
Permissions issue for spark.write

### ISSUE THREAD

**Issue by tristenwentling** [newfront/hitchhikers_guide_to_deltalake_streaming#4]
I think this one is specific to my environment but I wanted to capture it in case anyone else runs into it.

While running the econn notebook and trying to create the parquet version of the files it throws a permissions error.

Py4JJavaError: An error occurred while calling o79.save.
: ExitCodeException exitCode=1: chmod: changing permissions of '/opt/spark/work-dir/hitchhikers_guide/pre-processing/parquet': Operation not permitted

I think this might happen in relation to running docker for Windows with WSL2 backend.

Will add notes if I find a workaround otherwise I will refer to a more native integration.

**Comment by tristenwentling** [comment]
Note, not specific to the spark context, might need to figure out where the permissions issue comes from
`chmod: changing permissions of '/opt/spark/work-dir/hitchhikers_guide/': Operation not permitted`

https://stackoverflow.com/questions/69972807/chmod-error-while-writing-outputs-with-spark-on-kubernetes and similar suggest it could come from inherited permissions when files are copied in, might be worth trying

**Comment by tristenwentling** [comment]
Confirmed it only happens with Spark at least so I'm guessing there's probably a user permission that can be modified.
I created the df instead with:
```
from deltalake.writer import write_deltalake
import pandas as pd

ecomm_df = pd.read_csv(f"{dataset_dir}/{datasets[0]}")
write_deltalake(dataset_dir + "/parquet", data=ecomm_df, mode="overwrite")
```

**Comment by newfront** [comment]
that is interesting. The spark user should be inherited in the docker environment. I'll look into this issue as I resolve finishing touches on the first-steps before getting into more content. 

+1 for the issue.

**Comment by tristenwentling** [comment]
I created a direct translation of the spark code to avoid this potentially, though I imagine it would pop up again later, using as a workaround for now
```
from pyarrow._dataset_parquet import ParquetFileWriteOptions, ParquetFileFormat
from pyspark.sql.functions import to_date, to_timestamp
from deltalake.writer import write_deltalake
import pandas as pd

sink_dir = 'sm' if datasets[1].endswith('-sm.csv') else 'lg'
write_options = ParquetFileFormat().make_write_options(compression="zstd")

epdf = (
    ecomm_df
    .withColumn("event_time", to_timestamp(col("event_time"), "yyyy-MM-dd HH:mm:ss z"))
    .withColumn("event_date", to_date(col("event_time")))
    ).toPandas()

write_deltalake(
    f"{dataset_dir}/parquet/{sink_dir}",
    data=epdf,
    mode="append",
    partition_by=["event_date"],
    file_options=write_options
    )
```

**Comment by newfront** [comment]
This "should" be fixed with the latest commit. The local files have been changed to `0755` from `0644`.

If this continues to be a problem, then the solution seems to be to modify the project to drop the datasets into a Docker image that extends the delta-docker base image. Then permissions are all "the user".
